services:
  postgres:
    container_name: data-analysis-dashboard-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bin_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: