---
title: "Task_4_Encoding_Scaling"
author: "Juan Oosthuizen"
date: "`r Sys.Date()`"
output: html_document
---

# Initial Setup
```{r setup, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(readr)     # read_csv, write_csv
  library(dplyr)     # select, mutate, across, etc.
  library(rsample)   # initial_split, training, testing
  library(recipes)   # pre-processing pipeline
  library(knitr)     # pretty tables in report
})

# Directories
clean_dir <- "../../Data/02_Cleaned"
output_dir <- "../../Data/03_Scaled"

# List cleaned data-sets
cleaned_files <- list.files(clean_dir, pattern = "\\.csv$", full.names = TRUE)
cleaned_files
```




# Display column names and data types for all cleaned datasets
```{r inspect, message=FALSE, warning=FALSE}
for (file_path in cleaned_files) {
  dataset_name <- tools::file_path_sans_ext(basename(file_path))
  cat("Dataset:", dataset_name, "\n")
  
  # Load data-set
  df <- read_csv(file_path, show_col_types = FALSE)
  
  # Create table of column names and data types
  col_info <- data.frame(
    Column = names(df),
    DataType = sapply(df, class),
    stringsAsFactors = FALSE
  )
  
  print(col_info)
  cat("\n----------------------------------------\n\n")
}
```

# Transform and Encode All Categorical Variables with One-Hot Encoding
```{r encode_categorical, message=FALSE, warning=FALSE}
# Initialize list to store the encoded data-sets
encoded_datasets <- list()

for (file_path in cleaned_files) {
  
  # Load dataset
  df <- read_csv(file_path, show_col_types = FALSE)
  dataset_name <- tools::file_path_sans_ext(basename(file_path))
  
  # Identify categorical columns
  cat_cols <- df %>% select(where(~ is.character(.x) | is.factor(.x))) %>% names()
  
  if (length(cat_cols) > 0) {
    for(col in cat_cols){
      
      # One-hot encoding
      dummy_df <- model.matrix(~ . - 1, data = df[col]) %>% as.data.frame()
      
      # Clean column names
      colnames(dummy_df) <- make.names(colnames(dummy_df))
      
      # Bind dummy columns and remove original column
      df <- bind_cols(df, dummy_df)
      df[[col]] <- NULL
    }
  }
  
  # Store processed data-set
  encoded_datasets[[dataset_name]] <- df
  
  cat("One-hot encoded all categorical variables for dataset:", dataset_name, "\n")
}
```
